### ISSUE TITLE
Issue with gitlab auth

### ISSUE THREAD

**Issue by dbeniamine** [kanboard/plugin-gitlab-auth#11]
Hello,

I'm trying to setup gitlab auth (cloned from github) for kanboard (latest stable version, intalled today) with my gitlab instance.
I've configured an application in gitlab and reported the value correctly in kanboard as explained in the documentation, I'm also working with nice urls, so everything shoud work.
However when I try either to link my account or to login with gitlab I have the following error: `gitlab   Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.`.

I noticed that at that point the gitlab url was someting like: `https://<mygitlab_servr>/oauth/authorize?response_type=code&client_id=+<my_clientid>&redirect_uri=<my_kanboardserver>%2Foauth%2Fgitlab&scope=&state=<some_string>`

I was wondering why there was a `+` before the client ID so I manually removed it and ended up to a gitlab page asking me to confirme the authorization.
Still when I click on authorize, I end up in kanboard with an error `External authentication failed`.

Any idea what might be going on ?

**Comment by fguillot** [comment]
Maybe a typo for the clientID in Kanboard settings?

**Comment by dbeniamine** [comment]
So the `+` came from a leading space before the client ID, but event after changing that I still have the external authentication failed error ...

How can I debug it ?

**Comment by fguillot** [comment]
You can enable the debug mode in Kanboard and you will see the HTTP requests made to Gitlab. But, if all URLs and clientID/secret are defined correctly, it should work.

**Comment by dbeniamine** [comment]
So using the debug mode of kanboard I found that there was yet another space avec the api url, resulting in bad http requests.
Everything works fine now, thanks :)
