### ISSUE TITLE
docker and gitlab

### ISSUE THREAD

**Issue by jpahullo** [kanboard/plugin-gitlab-auth#2]
Hi!

I was trying kanboard oauth authentication via this plugin.

I installed kanboard via the docker image. I set up the settings of the integration via the data/config.php file as depicted in the README file.

However, kanboard always expects a URL like http://localhost/oauth/gitlab (since it is running in a docker image) and I cannot make it work, since at the end, when returning to kanboard, gitlab redirects to http://localhost/oauth/gitlab which does not exist, obviously.

My settings:

* Gitlab: http://{ip}:8079
* Kanboard: http://{ip}:8082

Since kanboard is running into a docker container, I always have the callback url: http://localhost/oauth/gitlab. This is the URL I have set up into gitlab. But in the last step of the OAuth process, I end up with a URL like http://localhost/oauth/gitlab?code={code}. At this stage, if I replace the localhost by {ip}:8082 the system states `External authentication failed`.

How could I use Gitlab OAuth?

I even tried to set into the docker image the nginx listening to the same http://{ip}:8082 to build the same URL as expected, but with same same bad result `External authentication failed`.

Thank you in advance.

Jordi

**Comment by fguillot** [comment]
You just need to define the Kanboard application URL in **Settings > Application settings > Application URL** with the value `http://{ip}:8082/`.

I updated the Readme, I hope it's more clear:
https://github.com/kanboard/plugin-gitlab-auth#custom-endpoints-for-self-hosted-gitlab
