### ISSUE TITLE
Auth Issue

### ISSUE THREAD

**Issue by rsliotta** [kanboard/plugin-gitlab-auth#3]
Hello.  I am trying to use the OAUTH and having an issue.
I set it up properly I believe.
When I try to log in I get this. https://www.evernote.com/l/AAGP7B7bvUxAy6eOr7Je2tejO2lYgHg2Ik8B/image.png
After I hit enter, I get this. https://www.evernote.com/l/AAERBygv-ZFPd57mPH2M1HlaOEx655hVUTMB/image.png

The wierd thing is when I log into gitlab, it shows authorized.

If you have a clue where I should look, that would be great...

**Comment by fguillot** [comment]
Did you link your Kanboard user profile successfully before the authentication step?

**Comment by rsliotta** [comment]
Frederic,

If only I read the manual properly.  I guess it took a 4th time to get it right!!!  Thanks for the assist.  Off to the webhook now.


Best Regards,

Bob Liotta
bob.liotta@rsliotta.com
(914) 414 5162
