### ISSUE TITLE
Support multiple services

### ISSUE THREAD

**Issue by jdoubleu** [kanboard/plugin-gitlab-auth#4]
So far you can only register one GitLab service.

There should be the possibility to register as much services as you want.
E.g.: I have an own GitLab instance running and use this as OAuth provider but additionally want GitLab.com to be one too.

**Comment by fguillot** [comment]
Well, this plugin can handle only one Gitlab instance. I don't have any plan to support multiple providers unless many people are interested by that or someone send a pull-request.
