### ISSUE TITLE
question: boards from gitlab

### ISSUE THREAD

**Issue by jpahullo** [kanboard/plugin-gitlab-auth#6]
Hi again!

One another question: how boards on kanboard are created from Gitlab projects automatically, and linked, so that any issue is a card into the corresponding board?

Thank you so much!

Jordi

**Comment by fguillot** [comment]
This plugin is only for the Gitlab authentication.

The plugin for Gitlab webhooks can create tasks automatically into Kanboard, see: https://kanboard.net/plugin/gitlab-webhook
