### ISSUE TITLE
Unable to use or link GitLab accounts, suspect HTTPS self-signed certificate verification error.

### ISSUE THREAD

**Issue by mirage335** [kanboard/plugin-gitlab-auth#7]
Every attempt to use or link a GitLab account fails with "External authentication failed". However, webhooks can be tested successfully. More significantly, Mattermost is successful in using GitLab OAuth with identical settings if self-signed certificates are enabled by configuration.

Watching the log files, this failure is consistently associated with the error message "[error] HttpClient: request failed" against the URLs referenced by "[debug] HttpClient: url=https://.domain:/oauth/token" and "[debug] HttpClient: url=https://.domain:/gitlab/api/v3/user". Since these URLs apparently match correct settings from another client, the failure to connect seems likely to result from the lack of an option to accept self-signed SSL certificates.

Kanboard, GitLab, and Mattermost are all behind an NGINX reverse proxy, providing the SSL service. Apache mod rewrite is enabled and seems to be working. Kanboard and GitLab are accessed through subdirectories "/kanboard" and "/gitlab" respectively. Mattermost has been permitted to use the root "/" directory.

Would like to debug this further in any way possible. First choice would be simply to disable SSL verification to confirm this is indeed the problem. Unfortunately, applying "openssl.verify_peer = False" and "openssl.verify_peer_name = False" to php.ini had no effect. Setting "openssl.cafile" may be another solution. Obtaining more descriptive debug logging beyond "request failed" would be useful as well.

Any help is appreciated.

[log.txt](https://github.com/kanboard/plugin-gitlab-auth/files/257676/log.txt)

**Comment by mirage335** [comment]
Adding a few lines to app/Core/Http/Client.php seems to work.

```
            'ssl' => array(
                //'verify_peer' => $this->verifySslCertificate,
                //'verify_peer_name' => $this->verifySslCertificate,
                'verify_peer' => false,
                'verify_peer_name' => false
            )
```

**Comment by francoisprunier** [comment]
No need to change the code: I was able to modify config.php to add: `define('HTTP_VERIFY_SSL_CERTIFICATE', false);` 
and I didn't get any more errors 'request failed'. 

Now I'm stuck a bit further though, gitlab has replied fine according to the logs, but i still get a `External authentication failed`

**Comment by fguillot** [comment]
I improved the documentation in case you still have a problem: https://kanboard.net/plugin/gitlab-auth

To disable SSL check, use the parameter `HTTP_VERIFY_SSL_CERTIFICATE` like mentioned above
