### ISSUE TITLE
External authentication failed

### ISSUE THREAD

**Issue by loranger** [kanboard/plugin-gitlab-auth#9]
Hello,

I did setup a self-hosted Gitlab and wanted to link a kanboard on the same server.
They both uses a custom sub-domain with a TLS certificate (thanks let's encrypt) and both works perfectly.
I've enable the rewrite setting and my nginx is well configured.
Kanboard is an OAuth application inside my Gitlab and uses the rewrited url :
![](https://dl.dropboxusercontent.com/s/r4o20dy6zxh8ps3/Edit__Kanboard__Applications__Admin_Area__GitLab_2016-06-27_11-33-52.png?dl=0)
Gitlab integration seems to be defined as expected :
![](https://dl.dropboxusercontent.com/s/ttpex8m70jzwl2f/Settings__Integrations_2016-06-27_11-35-13.png?dl=0)

But as you can see on [this screencast](http://take.ms/x4SY5), I can't make it work.

I tried to disabled the ssl certificate verification, but it didn't help.
I can't find any error from the logs.

Did I miss something important ?

**Comment by fguillot** [comment]
Did you link your Kanboard account to your Gitlab account before? (User profile > external accounts)

**Comment by rokube** [comment]
I'm having the same issue.

I did create a new external user in Kanboard for the existing Gitlab user, using the exact Username, Name and Email settings.

Apparently linking the account worked as well, as I see under: **User settings -> External accounts** that the Gitlab account is linked. However after login out and trying to use the Gitlab login, the error is *External authentication failed*

**Comment by rokube** [comment]
I could resolve the issue, at least in my case.

Apparently I was using the wrong `Gitlab Id` when creating a new **remote** user in Kanboard. The `Gitlab Id` is the Gitlab user ID, which you can obtain, e.g. using the Gitlab API. The 

`curl --header "PRIVATE-TOKEN: <your_private_gitlab_token>" "https://your.gitlab.host/api/v3/users"`

I was not able to spot the user ID, using the Gitlab web interface. Maybe I was blind 😄 

If this resolves this issue for others. Maybe it helps to be point this out in the documentation as well.

**Comment by fguillot** [comment]
I improved the documentation in case you still have problem to setup everything: https://kanboard.net/plugin/gitlab-auth

**Comment by loranger** [comment]
Hi, That's exactly what I was missing.

Thank you so much !!
